name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rauth python-dateutil pydantic pygments pytz pandas pytest sortedcontainers
      - name: Run tests
        run: |
          export PYTHONPATH=./src
          python -m pytest
